name: hahaha_flashcard
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  path: ^1.8.3
  image: ^4.1.3
  google_mlkit_text_recognition: ^0.13.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  firebase_auth: ^5.3.1
  intl: ^0.19.0
  receive_sharing_intent: ^1.7.1
  fl_chart: ^0.68.0
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  flutter_tts: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - .env

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/HaHaHaFlashCard.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/HaHaHaFlashCard.png"

